# Spring configuration
spring:
  # Database configurations
  datasource:
    url: jdbc:postgresql://localhost:5432/
    username: postgres
    password: kla4st#en
  # Flyway configuration
  flyway.locations: classpath:db/local_migrations