# This job sends the maven dependency tree of the project to Github
# for further security analysis.

name: "MavenDepTreeSubmission"

on:
    push:
        branches: [ "main" ]

jobs:
    build:

        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v3
            -   name: Set up JDK 17
                uses: actions/setup-java@v3
                with:
                    java-version: '17'
                    distribution: 'temurin'
                    cache: maven
            -   name: Maven Dependency Tree Dependency Submission
                uses: advanced-security/maven-dependency-submission-action@v4.0.0